name: "Copilot auto-fix"
description: "Raise issues that GitHub's Coding Agent can implement immediately"
labels:
  - copilot-ready
  - needs-triage
body:
  - type: markdown
    attributes:
      value: |
        GitHub now prioritises issues that Copilot Coding Agents can solve autonomously. Use this form to describe a **small, deterministic change** with clear success criteria so the agent can pick it up straight away.

        > ℹ️ Provide everything the agent needs (context, files, commands). Maintainers will review afterwards, but Copilot should be able to ship the fix without waiting for a human.
  - type: checkboxes
    id: readiness
    attributes:
      label: Automation readiness
      description: These are derived from GitHub's internal Copilot triage rules. Please confirm all of them.
      options:
        - label: The change is limited in scope (one feature, bug, or documentation fix)
          required: true
        - label: Steps to reproduce or verify are deterministic and available to the agent
          required: true
        - label: The affected files and commands are safe for automated changes (no credentials, secrets, or manual approvals)
          required: true
        - label: Existing tests cover the change or clear acceptance criteria are provided
          required: true
  - type: input
    id: summary
    attributes:
      label: One-line summary
      description: A short title the Copilot agent can turn into a branch/commit message.
      placeholder: "Fix prompt metadata typo in python instructions"
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Background / context
      description: Why is this needed? Reference spec IDs, ADRs, or files so the agent can fetch the right prompts.
      placeholder: |
        e.g. "Identifier [ID-<prefix>-NNN] references outdated behaviour. Update python.instructions.md section 0 to match the constitution."
      value: |
        - Problem statement
        - Links to relevant specs / docs
        - Any prior discussions
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce or verify
      description: Copilot will follow these exactly. Use numbered steps with expected/actual outcomes.
      placeholder: |
        1. Run `make count-tokens`
        2. Observe that python instructions are missing from the output
    validations:
      required: true
  - type: textarea
    id: success
    attributes:
      label: Acceptance criteria
      description: List the observable outcomes the agent must satisfy (bullet list recommended).
      placeholder: |
        - Token report includes python instructions
        - `make lint && make test` passes
    validations:
      required: true
  - type: textarea
    id: files
    attributes:
      label: Files or directories involved
      description: Enumerate the exact paths the agent may edit. Anything not listed will be treated as read-only.
      placeholder: |
        - .github/instructions/python.instructions.md
        - README.md
    validations:
      required: true
  - type: textarea
    id: commands
    attributes:
      label: Commands to run
      description: Shell commands Copilot should execute to validate the fix. Include lint/tests or custom scripts.
      placeholder: |
        make lint
        make test
      value: |
        make lint
        make test
    validations:
      required: true
  - type: checkboxes
    id: confirmation
    attributes:
      label: Author confirmation
      description: Final confirmation for Copilot auto-delegation.
      options:
        - label: I approve GitHub Copilot Coding Agent to implement this issue automatically and create a PR when checks pass.
          required: true
        - label: I will review the PR produced by Copilot promptly once notified.
          required: true
