#!/bin/bash

# WARNING: Please DO NOT edit this file! It is maintained in the [repository name] (https://github.com/org/repo). Raise a PR instead.

set -euo pipefail

# Short description of what this script does. This is a <tool> command wrapper.
# It will run <tool> natively if it is installed, otherwise it will run it in
# a Docker container.
#
# Usage:
#   $ [options] ./script-name.sh
#
# Options:
#   file=path/to/file       # Description, default is 'default-value'
#   FORCE_USE_DOCKER=true   # If set to true the command is run in a Docker container, default is 'false'
#   VERBOSE=true            # Show all the executed commands, default is 'false'
#
# Exit codes:
#   0 - Success
#   1 - Failure

# ==============================================================================

function main() {

  cd "$(git rev-parse --show-toplevel)"

  local file=${file:-default-value}
  if command -v toolname > /dev/null 2>&1 && ! is-arg-true "${FORCE_USE_DOCKER:-false}"; then
    file="$file" run-tool-natively
  else
    file="$file" run-tool-in-docker
  fi
}

# Run tool natively.
# Arguments (provided as environment variables):
#   file=[path to the file]
function run-tool-natively() {

  toolname "$file"
}

# Run tool in a Docker container.
# Arguments (provided as environment variables):
#   file=[path to the file]
function run-tool-in-docker() {

  # shellcheck disable=SC1091
  source ./scripts/docker/docker.lib.sh

  # shellcheck disable=SC2155
  local image=$(name=org/toolname docker-get-image-version-and-pull)
  docker run --rm --platform linux/amd64 \
    --volume "$PWD":/workdir \
    "$image" \
      toolname "/workdir/$file"
}

# ==============================================================================

function is-arg-true() {

  if [[ "$1" =~ ^(true|yes|y|on|1|TRUE|YES|Y|ON)$ ]]; then
    return 0
  else
    return 1
  fi
}

# ==============================================================================

is-arg-true "${VERBOSE:-false}" && set -x

main "$@"

exit 0
